#####################################################################
#
# INPUT_DIR: Input directory for images
# OUTPUTDIR: Output direcotry to save processed images
#
#####################################################################
INPUT_DIR = "./input/"
OUTPUT_DIR = "./output/"
CSV_FILE = "features.csv"


#################################################
# COLOR_CHANNEL: Color channel "R", "B" or "G"
#################################################
COLOR_CHANNEL = "G"


#####################################################################
# KNN
#####################################################################
K_MAX_BOUND = 5
FOLDS = 10